spring:
  application:
    name: notesapi
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://NMVlrypYLuxGqCoAaCUayxuDxue7XFtA@dpg-cqbcvh8gph6c73fqus30-a.oregon-postgres.render.com/notedb_0vd5
    username: notedb_0vd5_user
    password: NMVlrypYLuxGqCoAaCUayxuDxue7XFtA
  jpa:
    database-platform: org.speer.assessment.configs.CustomPostgreSQLDialect
    open-in-view: true
    hibernate:
      ddl-auto: validate  # use update to enable DDL handling
    show-sql: false
    properties:
      hibernate:
        format_sql: true
security:
  jwt:
    secret-key: 3cd79fc2edd89fb57df9a8f36a72ea3873153b5900271ab8c45b4f8a8368d639
    # 24h in millisecond
    expiration-time: 86400000
web:
  ratelimiter:
    qps: 1
    timeout: 1
logging:
  file:
    name: ./logs/notesapi.log